# MariaDB 최신 버전을 베이스 이미지로 사용
FROM mariadb:latest

# 루트 사용자가 비밀번호 없이 로그인할 수 있도록 환경 변수 설정
ENV MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1

run docker-entrypoint.sh mysqld

# 실행 스크립트를 컨테이너에 복사
# COPY run_sql.sh /usr/local/bin/run_sql.sh

# 컨테이너의 작업 디렉토리 설정
WORKDIR /exam

# 컨테이너 시작 시 실행될 기본 명령어 설정
ENTRYPOINT ["mariadb"]

# 사용자가 컨테이너 실행 시 전달하는 인자(쿼리 파일)를 받기 위해 CMD는 비워둡니다.
CMD []


# docker build -t container_sql:latest -f Dockerfile_sql .

# docker run --rm -v vol-onCoTe-storage:/exam container_sql:latest your_query.sql