# 베이스 이미지 설정
FROM openjdk:17-jdk-slim

# 저장소 볼륨 설정
VOLUME ["/exam"]

# 코드 실행
WORKDIR /exam

ENTRYPOINT ["java"]
CMD ["java.java"]


# 이미지 생성
# docker build -t container_java:latest -f Dockerfile_java .

# 컨테이너 실행
# docker run --rm --network net-onCoTe -v vol-onCoTe-storage:/exam container_java:latest 

# import java.io.*;
# class Main {
#     public static void main(String... args) {
#         System.out.println("ballboy");
#     }
# }