# 베이스 이미지 설정
FROM python:3.13.5-alpine

# 저장소 볼륨 설정
VOLUME ["/exam"]

# 코드 실행
WORKDIR /exam

ENTRYPOINT ["python"]
CMD ["python.py"]

# 이미지 생성
# docker build -t container_py:latest -f Dockerfile_py .

# 컨테이너 실행
# docker run --rm --network net-onCoTe -v vol-onCoTe-storage:/exam container_py:latest 
