FROM gcc:12.4.0-bookworm

# 저장소 볼륨 설정
VOLUME ["/exam"]

# 코드 실행
WORKDIR /exam

ENTRYPOINT ["./run_c.sh"]
CMD ["clang.c"]


# 이미지 생성
# docker build -t container_c:latest -f Dockerfile_c .

# 컨테이너 실행
# docker run --rm --network net-onCoTe -v vol-onCoTe-storage:/exam container_c:latest 

